//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ordenes.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLE_ORDEN
    {
        public int ID { get; set; }
        public Nullable<int> CLIENTE_ID { get; set; }
        public Nullable<int> USUARIO_ID { get; set; }
        public Nullable<System.DateTime> FECHA_ORDEN { get; set; }
        public Nullable<System.DateTime> FECHA_INICIO { get; set; }
        public Nullable<System.DateTime> FECHA_FIN { get; set; }
        public string ESTADO { get; set; }
        public Nullable<int> PRODUCTO_ID { get; set; }
        public Nullable<double> CANTIDAD { get; set; }
        public string MEDIDA { get; set; }
        public Nullable<double> ALTO { get; set; }
        public Nullable<double> ANCHO { get; set; }
        public Nullable<double> ANCHO_BS { get; set; }
        public Nullable<double> LARGO_BS { get; set; }
        public Nullable<double> ANCHO_BN { get; set; }
        public Nullable<double> LARGO_BN { get; set; }
        public string COMENTARIO { get; set; }
    
        public virtual CLIENTES CLIENTES { get; set; }
        public virtual PRODUCTOS PRODUCTOS { get; set; }
        public virtual USUARIOS USUARIOS { get; set; }
    }
}
